import { ThemeProvider } from '@/components/ThemeProvider';
import './globals.css';
import type { Metadata } from 'next';
import { Anek_Bangla } from 'next/font/google';
import Header from '@/components/Header';
import 'highlight.js/styles/a11y-dark.css';

const albert_sans = Anek_Bangla({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={albert_sans.className} suppressHydrationWarning data-theme="second-theme">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <div className="container h-[calc(100vh-80px)]">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
